# Main application configuration for your ADK project

app:
  name: PersonalHelperAgent
  env: development            # dev / staging / production

  model: gemini-2.5-flash     # default model used across all agents

agents:
  assistant:
    model: gemini-2.5-flash
    temperature: 0.4
    top_p: 0.95


# Logging configuration (useful for future expansion)
logging:
  level: INFO                 # DEBUG / INFO / WARNING / ERROR
  save_to_file: false         # set true if you want logs saved later
  #file_path: logs/app.log     # will matter only if save_to_file = true

# Reserved section for future global configurations
services:
  enable_google_search: false  # assistant uses built-in google_search
  enable_math_tools: true     # for calc_tools
  enable_time_tools: true     # for time_tools



