app:
  name: PersonalHelperAgent
  env: development

  model: gemini-2.5-flash     # default model used across all agents

agents:
  assistant:
    model: gemini-2.5-flash
    temperature: 0.4
    top_p: 0.95



logging:
  level: INFO
  save_to_file: false         
  #file_path: logs/app.log


services:
  enable_google_search: false
  enable_math_tools: true     # for calc_tools
  enable_time_tools: true     # for time_tools



